### ISSUE TITLE
CLI docgen

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/monorepo#4]
Create a CLI command for generate API docs.

**Comment by krisbitney** [comment]
This issue is now referenced in issue https://github.com/polywrap/monorepo/issues/702

The CLI docgen command should be able to produce documentation--at minimum an interface--for any wrapper remotely, so that any app developer can generate documentation for any wrapper. This can be implemented in a manner similar to that of the CLI app command.

**Comment by dOrgJelli** [comment]
Closed by: https://github.com/polywrap/monorepo/pull/820
